# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gcpql < Formula
  desc ""
  homepage "https://github.com/moshebe/gcpql"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/moshebe/gcpql/releases/download/v0.0.1/gcpql_Darwin_x86_64.tar.gz"
      sha256 "4485695bed5e3ca5ad07f8f6973b83e1e6cd59dcb7fd3ed292ca1e6a1712b62e"

      def install
        bin.install "gcpql"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/moshebe/gcpql/releases/download/v0.0.1/gcpql_Darwin_arm64.tar.gz"
      sha256 "ba49109def823836b5a81e1c8927fb0773958af676eadbada08eb0f87859fbcb"

      def install
        bin.install "gcpql"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/moshebe/gcpql/releases/download/v0.0.1/gcpql_Linux_x86_64.tar.gz"
      sha256 "72e81c585f7282036236102fefd9a953dfdb5fe66f4c4380aa1ea1c27dc450f0"
      def install
        bin.install "gcpql"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/moshebe/gcpql/releases/download/v0.0.1/gcpql_Linux_arm64.tar.gz"
      sha256 "3e6f28c95a0a74e29c18b255350e0f9cb9bfefa5cf71a48590ba29bfd8cd21b6"
      def install
        bin.install "gcpql"
      end
    end
  end
end
