# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gcpql < Formula
  desc ""
  homepage "https://github.com/moshebe/gcpql"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/moshebe/gcpql/releases/download/v0.0.2/gcpql_Darwin_x86_64.tar.gz"
      sha256 "ca2823cf5a60436f1a0bdf00941b0a2b9b7bec57406c1f148447753e532167db"

      def install
        bin.install "gcpql"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/moshebe/gcpql/releases/download/v0.0.2/gcpql_Darwin_arm64.tar.gz"
      sha256 "37cc30a64fcd39b770dca1207be4d650f4c3dc6e31cb4c1f9d24d628f8c63838"

      def install
        bin.install "gcpql"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/moshebe/gcpql/releases/download/v0.0.2/gcpql_Linux_x86_64.tar.gz"
      sha256 "2fbcdf7b74f52265d1de40587a883a8fc1c664474071b1d6b82d638b291f9953"
      def install
        bin.install "gcpql"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/moshebe/gcpql/releases/download/v0.0.2/gcpql_Linux_arm64.tar.gz"
      sha256 "ed5baa6e16b1e863f9dbc67cff73c92f69c2fc631dff3a3717a8263ddb74616f"
      def install
        bin.install "gcpql"
      end
    end
  end
end
