# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gcpql < Formula
  desc ""
  homepage "https://github.com/moshebe/gcpql"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/moshebe/gcpql/releases/download/v0.0.2/gcpql_Darwin_x86_64.tar.gz"
      sha256 "9a86f92e5a96c64899eccc942f1225476eec288bd071ac017c9c8d34ae9486bf"

      def install
        bin.install "gcpql"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/moshebe/gcpql/releases/download/v0.0.2/gcpql_Darwin_arm64.tar.gz"
      sha256 "1f306e81b90164890d6ffa16245d602a2011972e7ec47d600dc2538d8842e126"

      def install
        bin.install "gcpql"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/moshebe/gcpql/releases/download/v0.0.2/gcpql_Linux_x86_64.tar.gz"
      sha256 "41c99018bb0de07d109a53e21baeeb72aba759f1e65dbdef8789aa1d091bba67"
      def install
        bin.install "gcpql"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/moshebe/gcpql/releases/download/v0.0.2/gcpql_Linux_arm64.tar.gz"
      sha256 "5e967ab15fa2036965d35770c37ed0b4748af03994507087db8f9b590c90b817"
      def install
        bin.install "gcpql"
      end
    end
  end
end
