# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gtrace < Formula
  desc ""
  homepage "https://github.com/moshebe/gtrace"
  version "1.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/moshebe/gtrace/releases/download/v1.0.5/gtrace_Darwin_x86_64.tar.gz"
      sha256 "b2282a1e389b1ac6d074ffcacaf1c3a803a9c6e2e337cf90b64f5d0629e5becb"

      def install
        bin.install "gtrace"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/moshebe/gtrace/releases/download/v1.0.5/gtrace_Darwin_arm64.tar.gz"
      sha256 "3bc51592519e87e6b3cdb67f169c06d611aa0376f2b7859d46ab1c3edc1889ef"

      def install
        bin.install "gtrace"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/moshebe/gtrace/releases/download/v1.0.5/gtrace_Linux_x86_64.tar.gz"
      sha256 "c621657c6e51318749b6361fe659c57080abc0b0009483cbe8be14e6de83d881"
      def install
        bin.install "gtrace"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/moshebe/gtrace/releases/download/v1.0.5/gtrace_Linux_arm64.tar.gz"
      sha256 "a9a0d216ce4c8c9876bf053b2bd206016ca1dfca07fdd6fb9b904e2cc27c37dd"
      def install
        bin.install "gtrace"
      end
    end
  end
end
